name: Release Node.js app

on:
  push:
    branches:
      - main
    paths:
      - 'node-dev-env/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: login to dockerhub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Build and push
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: /c/users/ed/desktop/dockertutorial/material-applications/node-dev-env
        push: true
        tags: ednawrocki/hello-docker-actions:latest